USE [acme]
GO

/****** Object:  Table [dbo].[TB_VOO]    Script Date: 7/7/2021 6:25:06 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TB_VOO](
	[ID_VOO] [int] IDENTITY(1,1) NOT NULL,
	[DATA_VOO] [datetime] NOT NULL,
	[CUSTO] [numeric](10, 2) NOT NULL,
	[DISTANCIA] [int] NOT NULL,
	[CAPTURA] [char](1) NOT NULL,
	[NIVEL_DOR] [int] NOT NULL,
 CONSTRAINT [PK_tbl_voo] PRIMARY KEY CLUSTERED 
(
	[ID_VOO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

